

name: Deploy to Firebase Hosting on PR (Staging)
on: 
  pull_request:
    branches:
      - staging
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: npm ci  &&  npm run build-ci:staging
      # - run: npm ci  &&  npm run build-ci:staging--TEMP
      - run: npm ci  &&  echo \"$FIREBASE_TOKEN\"  &&  echo ${{ secrets.FIREBASE_TOKEN }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JAILBREAK_GAME__STAGING }}'
          projectId: jailbreak-game--staging
